FROM apache/airflow:2.9.3-python3.11

USER airflow

COPY requirements/base.txt .
COPY requirements/airflow.txt .

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r base.txt \
    && pip install --no-cache-dir -r airflow.txt

USER airflow

EXPOSE 8080

CMD ["airflow", "standalone"]
