FROM python:3.11-slim

WORKDIR /dashboard

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements/base.txt .
COPY requirements/streamlit.txt .

RUN pip install --upgrade pip \
    && pip install -r base.txt \
    && pip install -r streamlit.txt

COPY dashboard/ /dashboard/

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0"]
